language: node_js
script: echo "Running tests against $(node -v)..."
jobs:
  include:
    - stage: test
      script: npm test
      node_js:
        - "lts/dubnium"
        - "lts/erbium"
        - "node"
    - stage: coverage
      script: npm test && npm run coverage
      node_js:
        - "lts/*"
    - stage: lint
      script: npm run lint
      node_js:
        - "lts/*"
    - stage: audit
      script: npm run audit
      node_js:
        - "lts/*"
